# Generated by Django 5.1.6 on 2025-03-11 12:59

import pgvector.django
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=300, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=300, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=300, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=300, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=300, null=True),
        ),
    ]
