# Generated by Django 5.1.6 on 2025-03-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('response_text', models.TextField()),
                ('query_type', models.CharField(choices=[('sql', 'SQL Query'), ('vector', 'Vector Query'), ('auto', 'Auto Query')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Query histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
