# Generated by Django 5.1.6 on 2025-03-24 18:48

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeshop', '0002_employeerole_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventoryrequirement',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
