# Generated by Django 5.1.6 on 2025-03-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeshop', '0003_productinventoryrequirement_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerole',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='productinventoryrequirement',
            name='embedding',
        ),
    ]
