# Generated by Django 5.1.6 on 2025-03-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeshop', '0004_remove_employeerole_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_indexed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
