# Generated by Django 5.1.6 on 2025-03-26 08:21

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeshop', '0005_product_last_indexed'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
